config/routes.rb
Rails.application.routes.draw do

  get 'pages/contact', to: 'pages#contact'

  resources :exhibits
  resources :stylists
  resources :services
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exhibit.rb
class Exhibit < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/stylist.rb
class Stylist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/exhibits_controller.rb
class ExhibitsController < ApplicationController
	before_action :set_exhibit, only: [:edit, :update, :destroy]
	def index
		@exhibits = Exhibit.all
	end

	def new
		@exhibit = Exhibit.new
	end

	def create
		@exhibit = Exhibit.new(exhibit_params)
		if @exhibit.save
			redirect_to exhibits_path
		else
			render :new
		end

	end

	def edit
	end

	def update
		if @exhibit.save
			redirect_to exhibits_path
		else
			render :edit
		end
	end

	def destroy
		
		@exhibit.delete
		redirect_to exhibits_path
	end

	private

	def set_exhibit
		@exhibit = Exhibit.find(params[:id])
	end

	def exhibit_params
		params.require(:exhibit).permit(:photo, :artist)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	before_action :set_service, only: [:edit, :update, :destroy]
	def index
		@services = Service.all
	end

	def new
		@service = Service.new
	end

	def create
		@service = Service.new(service_params)
		if @service.save
			redirect_to services_path
		else
			render :new
		end

	end

	def edit
	end

	def update
		if @service.save
			redirect_to services_path
		else
			render :edit
		end
	end

	def destroy
		
		@service.delete
		redirect_to services_path
	end

	private

	def set_service
		@service = Service.find(params[:id])
	end

	def service_params
		params.require(:service).permit(:title, :description, :image)
	end
	
end

app/controllers/stylists_controller.rb
class StylistsController < ApplicationController
	before_action :set_stylist, only: [:edit, :update, :destroy]
	def index
		@stylists = Stylist.all
	end

	def new
		@stylist = Stylist.new
	end

	def create
		@stylist = Stylist.new(stylist_params)
		if @stylist.save
			redirect_to stylists_path
		else
			render :new
		end

	end

	def edit
	end

	def update
		if @stylist.save
			redirect_to stylists_path
		else
			render :edit
		end
	end

	def destroy
		
		@stylist.delete
		redirect_to stylists_path
	end

	private

	def set_stylist
		@stylist = Stylist.find(params[:id])
	end

	def stylist_params
		params.require(:stylist).permit(:name, :bio, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def image_generator(height:, width:)
		"http://placehold.it/#{height}x#{width}"
	end
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper

end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/views/exhibits/_form.html.erb
<%= form_for @exhibit do |f| %>

	<div>
		<%= f.label :photo %>

		<%= f.text_field :photo %>
	</div>

	<div>
		<%= f.label :artist %>

		<%= f.text_field :artist %>
	</div>

	<%= f.submit 'Save Exhibit Item' %>

<% end %>

app/views/exhibits/edit.html.erb
<%= render 'form' %>

app/views/exhibits/index.html.erb
<h1>I am the Gallery page</h1>
<%= link_to "Create a New Exhibit Item", new_exhibit_path %>
<% @exhibits.each do |exhibit| %>
	<div>
		<div><%=  image_tag exhibit.photo %></div>
		<div><%= exhibit.artist %></div>
		<%= link_to "Edit Exhibit", edit_exhibit_path(exhibit) %>
		<%= link_to "Delete Exhibit", exhibit_path(exhibit), method: :delete, id: "delete_exhibit_#{exhibit.id}_from_index", data: { confirm: 'Are you sure?' } %>
	</div>
<% end %>

app/views/exhibits/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NailsOn9th</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <div> </div>
    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/services/_form.html.erb
<%= form_for @service do |f| %>

	<div>
		<%= f.label :title %>

		<%= f.text_field :title %>
	</div>

	<div>
		<%= f.label :description %>

		<%= f.text_area :description %>
	</div>

	<div>
		<%= f.label :image_stuffs %>

		<%= f.text_field :image %>
	</div>

	<%= f.submit 'Save Service' %>

<% end %>

app/views/services/edit.html.erb
<%= render "form" %>

app/views/services/index.html.erb
<h1>I am the services page</h1>
<%= link_to "Create a New Service", new_service_path %>
<% @services.each do |service| %>
	<div>
		<div><%=  image_tag service.image %></div>
		<div><%= service.title %></div>
		<div><%= service.description %></div>
		<%= link_to "Edit Service", edit_service_path(service) %>
		<%= link_to "Delete Service", service_path(service), method: :delete, id: "delete_service_#{service.id}_from_index", data: { confirm: 'Are you sure?' } %>
	</div>
<% end %>

app/views/services/new.html.erb
<%= render "form" %>

app/views/shared/_nav.html.erb
<div>
	<div>
		<%= link_to "Home", root_path %>
	</div>
	<div>
		<%= link_to "Services", services_path %>
	</div>
	<div>
		<%= link_to "Gallery", exhibits_path %>
	</div>
	<div>
		<%= link_to "Stylists", stylists_path %>
	</div>
	<div>
		<%= link_to "Contact", pages_contact_path %>
	</div>
</div>

app/views/stylists/_form.html.erb
<%= form_for @stylist do |f| %>

	<div>
		<%= f.label :image %>

		<%= f.text_field :image %>
	</div>

	<div>
		<%= f.label :name %>

		<%= f.text_field :name %>
	</div>

	<div>
		<%= f.label :bio %>

		<%= f.text_area :bio %>
	</div>

	<%= f.submit 'Save Stylist Info' %>

<% end %>

app/views/stylists/edit.html.erb
<%= render 'form' %>

app/views/stylists/index.html.erb
<h1>I am the Stylists page</h1>
<%= link_to "New Stylist", new_stylist_path %>
<% @stylists.each do |stylist| %>
	<div>
		<div><%=  image_tag stylist.image %></div>
		<div><%= stylist.name %></div>
		<div><%= stylist.bio %></div>
		<%= link_to "Edit Stylist's Info", edit_stylist_path(stylist) %>
		<%= link_to "Delete Stylist", stylist_path(stylist), method: :delete, id: "delete_stylist_#{stylist.id}_from_index", data: { confirm: 'Are you sure?' } %>
	</div>
<% end %>

app/views/stylists/new.html.erb
<%= render 'form' %>